
#ifndef NEEDLESEGMENTATIONWRAPPER_EXPORT_H
#define NEEDLESEGMENTATIONWRAPPER_EXPORT_H

#ifdef NEEDLESEGMENTATIONWRAPPER_STATIC_DEFINE
#  define NEEDLESEGMENTATIONWRAPPER_EXPORT
#  define NEEDLESEGMENTATIONWRAPPER_NO_EXPORT
#else
#  ifndef NEEDLESEGMENTATIONWRAPPER_EXPORT
#    ifdef NeedleSegmentationWrapper_EXPORTS
        /* We are building this library */
#      define NEEDLESEGMENTATIONWRAPPER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define NEEDLESEGMENTATIONWRAPPER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef NEEDLESEGMENTATIONWRAPPER_NO_EXPORT
#    define NEEDLESEGMENTATIONWRAPPER_NO_EXPORT 
#  endif
#endif

#ifndef NEEDLESEGMENTATIONWRAPPER_DEPRECATED
#  define NEEDLESEGMENTATIONWRAPPER_DEPRECATED __declspec(deprecated)
#  define NEEDLESEGMENTATIONWRAPPER_DEPRECATED_EXPORT NEEDLESEGMENTATIONWRAPPER_EXPORT __declspec(deprecated)
#  define NEEDLESEGMENTATIONWRAPPER_DEPRECATED_NO_EXPORT NEEDLESEGMENTATIONWRAPPER_NO_EXPORT __declspec(deprecated)
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define NEEDLESEGMENTATIONWRAPPER_NO_DEPRECATED
#endif

#endif
